Base Notification model
uclouvain/osis-notification pull request #2
Opened 2021-05-20 12:55 UTC by AL9000

2021-05-20 13:08 UTC, SebCorbin commented on models/notifications.py
> +        abstract = True
Pourquoi ?

2021-05-20 13:08 UTC, SebCorbin commented on models/notifications.py
> +    def process_notification(self):
Attention, le processing est décorélé du modèle, la classe abstraite dont on paralait est une classe qui n'est pas le modèle

2021-05-20 13:36 UTC, AL9000 commented on models/notifications.py
> +        abstract = True
Parce que j'ai oublié qu'on voulait tout dans la même table et donc que les classes Web Et Email seraient des proxy ^^'
Je refait ça !

2021-05-25 09:24 UTC, SebCorbin requested changes

2021-05-25 09:24 UTC, SebCorbin commented on contrib/models/email_notification.py
> +from osis_notification.models import EmailNotificationModel
Tu peux garder le nom du modèle comme `EmailNotification`et faire un `from osis_notification.models import EmailNotification as EmailNotificationModel`

2021-05-25 09:24 UTC, SebCorbin commented on contrib/models/email_notification.py
> +class EmailNotification(EmailNotificationModel):
Il faut vraiment que tu décorrele le modèle du métier, la classe métier n'hérite de rien, sauf potentiellement de ABC https://docs.python.org/3/library/abc.html

2021-05-25 09:24 UTC, SebCorbin commented on contrib/models/email_notification.py
> +        abstract = True
Comme elle n'hérite pas du modèle, ces deux lignes n'ont pas lieu d'être

2021-05-25 09:24 UTC, SebCorbin commented on contrib/models/email_notification.py
> +        self.save()
On a pas de mark as read pour l'e-mail (théoriquement impossible)

2021-05-25 09:24 UTC, SebCorbin commented on contrib/models/email_notification.py
> +        self.save()
Et ici pour découpler : reçois la notif (instance de modèle en paramètre) et modifie la (donc pas self)

2021-05-25 09:24 UTC, SebCorbin commented on contrib/models/web_notification.py
> +        self.save()
Idem ici reçois la notification en paramètre et modifie là

2021-05-25 09:24 UTC, SebCorbin commented on models/email_notification.py
> +class EmailNotificationModel(Notification):
Tu peux garder l'ancien nom, il ne doit être utilisé qu'en interne dans l'application de toute façon

2021-05-27 09:50 UTC, SebCorbin commented on contrib/handlers.py
> +        mail["Subject"] = "To define"  # TODO define this
C'est à rajouter au type principal `EmailNotificationType`

2021-05-27 09:50 UTC, SebCorbin commented on README.md
> +content = "This is the content of the email notification"
Ça pourrait être utile de rajouter un exemple utilisant osis-mail-template pour avoir une utilisation complète

2021-05-27 09:50 UTC, SebCorbin commented on contrib/handlers.py
> +    def process(notification):
À typer sur le modèle Django pour être sûr de ce qu'on reçoit

2021-05-27 09:50 UTC, SebCorbin commented on contrib/handlers.py
> +                receivers=[receiver, ],
`[receiver]`

2021-05-27 09:50 UTC, SebCorbin commented on contrib/handlers.py
> +                html_message=unescape(strip_tags(email_message.get("body"))),  # TODO
Idem, tout doit être dans le payload initial de la notification

2021-05-27 09:50 UTC, SebCorbin commented on models/email_notification.py
> +    def create(self, person: Person, payload: str):
Mieux vaut utiliser `**kwargs` pour garder la signature originale

2021-05-28 08:52 UTC, albrugnetti commented
Il a été convenu avec @AL9000  de merger cette PR. La problématique soulevée par Sébastien (_Utilisation EmailMessage pour futur intégration avec osis-mail-template_) sera traitée dans une autre PR

2021-05-28 08:52 UTC, merged