Add show more / show less on a notification
uclouvain/osis-notification pull request #20
Opened 2021-07-12 10:24 UTC by AL9000

2021-07-12 10:32 UTC, BenJneB approved these changes

2021-07-12 12:59 UTC, SebCorbin requested changes

2021-07-12 12:59 UTC, SebCorbin commented on package.json
> +    "vue-truncate-collapsed": "^3.0.1"
Ça devrait être une dépendance "brute", pas une dev, du coup ta réponse sur l'augmentation de la taille de paquet c'est peutre être pas quelques Ko :p

2021-07-13 07:36 UTC, AL9000 commented on package.json
> +    "vue-truncate-collapsed": "^3.0.1"
@SebCorbin ça ne change rien dans notre cas vu qu'on compile en mode lib non ?
Si je change et que j'ajoute ça aux `dependencies` j'ai : ` static/osis_notification/osis-notification.umd.min.js     | Bin 57266 -> 57198 bytes`

2021-07-13 08:18 UTC, SebCorbin approved these changes

2021-07-13 08:39 UTC, albrugnetti commented
@SebCorbin  @AL9000, je viens de me rendre compte que le repository ne disposent pas de **schema.yml** (OpenAPI)
Est-ce que vous pouvez l'ajouter? Ainsi que dans les autres repo ?

2021-07-13 08:53 UTC, merged