schema.yml
uclouvain/osis-notification pull request #21
Opened 2021-07-13 13:02 UTC by AL9000

2021-07-14 13:07 UTC, BenJneB commented
Il ne manquerais pas cet endpoint ?

```python3
    path(
        "mark_all_as_read",
        MarkAllNotificationsAsReadView.as_view(),
        name="notification-mark-all-as-read",
    )
```

2021-08-12 12:40 UTC, albrugnetti reviewed
Il manque les propriétés "**responses**" au niveau de chaque requête (cf. https://github.com/uclouvain/osis/blob/dev/attribution/schema.yml#L29)

2021-08-12 14:15 UTC, glamarca commented
Can one of the admins verify this patch?

2021-08-12 14:15 UTC, glamarca commented
Can one of the admins verify this patch?

2021-08-12 14:27 UTC, albrugnetti reviewed
Et n'oublie pas d'ajouter les paramètres pour préparer l'intégration avec l'ESB
parameters:
        - $ref: '#/components/parameters/Accept-Language'
        - $ref: '#/components/parameters/X-User-FirstName'
        - $ref: '#/components/parameters/X-User-LastName'
        - $ref: '#/components/parameters/X-User-Email'
        - $ref: '#/components/parameters/X-User-GlobalID'

(cf. https://github.com/uclouvain/osis/blob/dev/attribution/schema.yml#L385)

2021-08-12 14:27 UTC, albrugnetti commented on schema.yml
> +  - url: https://osis.uclouvain.be/
Tu peux remplacer en '**https://osis.uclouvain.be/api/v1/notification/**' et donc supprimer pour tous les autres endpoints (prefix: /notifications/v1)

2021-08-12 14:27 UTC, albrugnetti commented on schema.yml
> +  - url: https://{environment}.osis.uclouvain.be/
https://{environment}.osis.uclouvain.be/api/v1/notification/

2021-08-12 14:27 UTC, albrugnetti commented on schema.yml
> +      - v1
tags: 
 - notification

2021-08-12 14:27 UTC, albrugnetti commented on schema.yml
> +      operationId: v1_list
notification_list

2021-08-12 14:27 UTC, albrugnetti commented on schema.yml
> +      operationId: v1_partial_update
notification_partial_update

2021-08-12 14:27 UTC, albrugnetti commented on schema.yml
> +      operationId: v1_update
notification_update

2021-08-12 14:27 UTC, albrugnetti commented on schema.yml
> +      operationId: v1_mak_all_as_read
notification_mark_all_as_read

2021-08-12 14:27 UTC, albrugnetti commented on schema.yml
> +    NotificationList:
PaginatedNotificationList

2021-08-13 07:11 UTC, albrugnetti requested changes

2021-08-13 07:11 UTC, albrugnetti commented on schema.yml
> +        $ref: '#/components/schemas/AcceptedLanguageEnum'
Il te manque cette déclaration dans ton schéma **AcceptedLanguageEnum**

2021-08-13 07:12 UTC, albrugnetti requested changes

2021-08-13 07:12 UTC, albrugnetti commented on schema.yml
> +      - v1
tags:
      - notification

2021-08-13 07:12 UTC, albrugnetti commented on schema.yml
> +      - v1
tags:
      - notification

2021-08-13 07:12 UTC, albrugnetti commented on schema.yml
> +      - v1
tags:
      - notification

2021-08-13 08:45 UTC, albrugnetti approved these changes

2021-08-13 08:46 UTC, merged